"""GDPR Subject Access Request and Right to Erasure email templates."""

from string import Template
from typing import Optional

SAR_TYPES = ["access", "erasure", "portability"]

_ACCESS = """\
Subject: Subject Access Request – Article 15 GDPR / UK GDPR

Dear Privacy Team / Data Protection Officer,

I am writing to exercise my right of access under Article 15 of the General Data\
 Protection Regulation (GDPR) and/or UK GDPR.

I request a copy of all personal data that $company_name holds about me, including:

  • The categories and specific personal data processed
  • The purposes of processing and the legal basis for each
  • The recipients or categories of recipients to whom my data has been or will be disclosed
  • The retention period, or the criteria used to determine it
  • Information about automated decision-making, including profiling (Article 22)
  • Details of any international data transfers and the safeguards in place

My account is registered under: $user_email

Please respond within one calendar month (30 days) as required by law. I am happy\
 to provide reasonable proof of identity upon request.

Yours faithfully,
$user_name

---
Generated by app-audit · github.com/Matthias0x44/app-audit · GDPR Article 15
"""

_ERASURE = """\
Subject: Right to Erasure Request – Article 17 GDPR / UK GDPR

Dear Privacy Team / Data Protection Officer,

I am writing to exercise my right to erasure under Article 17 of the General Data\
 Protection Regulation (GDPR) and/or UK GDPR.

I request that $company_name permanently delete all personal data held about me, including:

  • My account and all profile information
  • All usage, behavioural, and analytics data
  • Any content I have created, uploaded, or contributed
  • Data shared with third-party processors on my behalf
  • Data held in backups, archives, or derived datasets

My account is registered under: $user_email

If you believe you have a legitimate legal ground to retain any data under Article 17(3),\
 please specify the exact legal basis in your response.

Please confirm in writing that my data has been deleted within one calendar month (30 days)\
 as required by law.

Yours faithfully,
$user_name

---
Generated by app-audit · github.com/Matthias0x44/app-audit · GDPR Article 17
"""

_PORTABILITY = """\
Subject: Right to Data Portability Request – Article 20 GDPR / UK GDPR

Dear Privacy Team / Data Protection Officer,

I am writing to exercise my right to data portability under Article 20 of the General Data\
 Protection Regulation (GDPR) and/or UK GDPR.

I request a machine-readable copy of all personal data I have provided to $company_name,\
 in a structured, commonly used format (preferably JSON or CSV).

My account is registered under: $user_email

Please provide the data via a secure download link or encrypted attachment.\
 Please respond within one calendar month (30 days) as required by law.

Yours faithfully,
$user_name

---
Generated by app-audit · github.com/Matthias0x44/app-audit · GDPR Article 20
"""

_TEMPLATES = {
    "access": _ACCESS,
    "erasure": _ERASURE,
    "portability": _PORTABILITY,
}


def generate_sar_email(
    company_name: str,
    user_name: str,
    user_email: str,
    request_type: str = "access",
    to_email: Optional[str] = None,
) -> str:
    body = Template(_TEMPLATES.get(request_type, _ACCESS)).safe_substitute(
        company_name=company_name,
        user_name=user_name,
        user_email=user_email,
    )
    if to_email:
        return f"To: {to_email}\n{body}"
    return body
